### ISSUE TITLE
Missing folder cardImages

### ISSUE THREAD

**Issue by arturs-berzins** [henrycharlesworth/big2_PPOalgorithm#2]
Running generateGUI.py results in
```diff
- FileNotFoundError: [Errno 2] No such file or directory: 'cardImages/1.png'
```
I believe you have forgotten to add the folder with the .png's to the repository.

I tested my own makeshift card-set and can confirm that the script ran with no further errors. I'd offer to push the cardImages I used, however I'm not sure of the deck indexing you use.

Cheers!

**Comment by henrycharlesworth** [comment]
That was stupid of me! I've added a folder now, thanks! :)

**Comment by arturs-berzins** [comment]
Thanks!
