### ISSUE TITLE
what is playersGo and goCounter

### ISSUE THREAD

**Issue by CesMak** [henrycharlesworth/big2_PPOalgorithm#7]
Hey there,

could you please describe what these paramters are:
playersGo
goCounter

**Comment by henrycharlesworth** [comment]
Hi! If I remember correctly playersGo is an integer identifying which of the four players turn it is, and goCounter simply counts the number of turns that have been played in the whole game (really just for monitoring game length).

**Comment by CesMak** [comment]
Thanks that helped me a lot.
